### ISSUE TITLE
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by luftwaffe808** [the-deep-learners/TensorFlow-LiveLessons#22]
I receive the error below from the server whenever I try to navigate to any notebooks through the Jupyter UI. A 500: Internal Server Error message also appears in a new browser tab.

I originally thought it may be an issue with the TensorFlow1.0 installation so I tried again with just 'tensorflow' but the error persists.

[E 18:51:28.099 NotebookApp] Uncaught exception GET /notebooks/work/notebooks/cartpole_dqn.ipynb (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/notebooks/work/notebooks/cartpole_dqn.ipynb', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 59, in get
        get_custom_frontend_exporters=get_custom_frontend_exporters
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/handlers.py", line 467, in render_template
        return template.render(**ns)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}
      File "/opt/conda/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 19, in get_custom_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/opt/conda/lib/python3.6/site-packages/nbconvert/__init__.py", line 7, in <module>
        from . import postprocessors
      File "/opt/conda/lib/python3.6/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
        from .serve import ServePostProcessor
      File "/opt/conda/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
        class ProxyHandler(web.RequestHandler):
      File "/opt/conda/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
        @web.asynchronous
    AttributeError: module 'tornado.web' has no attribute 'asynchronous'
[E 18:51:28.115 NotebookApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8888/tree/work/notebooks",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,en-GB;q=0.8",
      "Cookie": "_xsrf=2|8451cf07|677ca621c29f86acbc87464ba9e92f25|1551993854; username-127-0-0-1-8888=\"2|1:0|10:1552071082|23:username-127-0-0-1-8888|44:NzAzZmJjMGNmNWE0NDBkNDhiZDA1NTAzMmU4YTY5YmI=|64ce7954a09e974e5014ed803858785b88b1a04e0d99c8f796a0f7bdc8e32410\""
    }
[E 18:51:28.115 NotebookApp] 500 GET /notebooks/work/notebooks/cartpole_dqn.ipynb (172.17.0.1) 176.96ms referer=http://127.0.0.1:8888/tree/work/notebooks

**Comment by jonkrohn** [comment]
Hey there @luftwaffe808 -- this is a common issue related to Tornado version incompatibilities with particular Jupyter versions. Are you following my Docker installation instructions exactly or are you setting up your own configuration?

**Comment by luftwaffe808** [comment]
I followed the instructions exactly. A colleague ran through everything and
didn’t have the same problem. I ended up using Godefroy‘s pre-built image
and everything works great.

**Comment by jonkrohn** [comment]
Huh! Interesting. Well, thanks for letting me know @luftwaffe808 ... I'll close this for the time being.

**Comment by jonkrohn** [comment]
I'm glad the pre-built images are working out for you 😃
