### ISSUE TITLE
getting error while installing tensorflow

### ISSUE THREAD

**Issue by vikramkon** [the-deep-learners/TensorFlow-LiveLessons#9]
On running the following command  ( on Mac)
sudo docker build -t tensorflow-ll-stack .

getting the following exception 
Step 5/9 : RUN pip install tflearn==0.3.2
 ---> Running in 3d5758f37abe
Collecting tflearn==0.3.2
  Downloading tflearn-0.3.2.tar.gz (98kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2533, in _dep_map
    return self.__dep_map
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2608, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2874, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'\x00\x00\x00\x00\x00\x00\x00\x00'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/opt/conda/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 699, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2757, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2547, in _dep_map
    dm.setdefault(extra, []).extend(parse_requirements(reqs))
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2867, in parse_requirements
    yield Requirement(line)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2876, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'\x00\x00\x00\x00\x00\x00\x00\x00'"
The command '/bin/sh -c pip install tflearn==0.3.2' returned a non-zero code: 2

**Comment by jonkrohn** [comment]
Hi @vikramkon, I haven't come across this error before. I re-ran the [install instructions](https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/installation/step_by_step_MacOSX_install.md) myself on a Mac a moment ago myself without issue: 

```
jon$ git clone https://github.com/the-deep-learners/TensorFlow-LiveLessons.git
Cloning into 'TensorFlow-LiveLessons'...
remote: Counting objects: 985, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 985 (delta 1), reused 4 (delta 1), pack-reused 980
Receiving objects: 100% (985/985), 2.36 MiB | 9.62 MiB/s, done.
Resolving deltas: 100% (654/654), done.

jon$ source TensorFlow-LiveLessons/installation/let_jovyan_write.sh

jon$ cd TensorFlow-LiveLessons

jon$ sudo docker build -t tensorflow-ll-stack .
Sending build context to Docker daemon  4.645MB
Step 1/9 : FROM jupyter/scipy-notebook
 ---> b92047368f8b
Step 2/9 : MAINTAINER Jon Krohn <jon@untapt.com>
 ---> Using cache
 ---> 167e61290a54
Step 3/9 : USER $NB_USER
 ---> Using cache
 ---> 67cf0e4e1bc2
Step 4/9 : RUN conda install --quiet --yes 'tensorflow=1.0*'
 ---> Using cache
 ---> 68be7863d8b4
Step 5/9 : RUN pip install tflearn==0.3.2
 ---> Using cache
 ---> 9e6d0612a208
Step 6/9 : RUN pip install keras==2.0.8
 ---> Using cache
 ---> 72161baadc9f
Step 7/9 : RUN pip install nltk==3.2.4
 ---> Using cache
 ---> 8111fc12c816
Step 8/9 : RUN pip install gensim==2.3.0
 ---> Using cache
 ---> a6f7bc110957
Step 9/9 : RUN pip install gym==0.9.4
 ---> Using cache
 ---> c571bd2300d7
Successfully built c571bd2300d7
Successfully tagged tensorflow-ll-stack:latest
```

If you delete the line causing you trouble from the [Dockerfile](https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/Dockerfile) (i.e., `RUN pip install tflearn==0.3.2`), what happens?

**Comment by vikramkon** [comment]
Hi jon,

Thank you it worked …May I ask what was the problem

Vikram

P.S : I am attending your NLP class tomorrow , maybe we talk about this after class

**Comment by jonkrohn** [comment]
We didn't solve the problem, @vikramkon, and I have no idea what the problem is. We deleted the line that was throwing an error, which means we lost its functionality. Chances are it's an edge case related to your particular machine or network, e.g., your employer is blocking the site from which the `tflearn` library is downloaded or something like that.
